XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share
XDG_CACHE_HOME=$HOME/.cache
XDG_STATE_HOME=$HOME/.local/state
XCOMPOSEFILE=$XDG_CONFIG_HOME/X11/xcompose

CARGO_HOME=$XDG_DATA_HOME/cargo
CARGO_TARGET_DIR=$XDG_CACHE_HOME/cargo-target
RUSTUP_HOME=$XDG_DATA_HOME/rustup

GOPATH=$XDG_DATA_HOME/go

JAVA_HOME=$HOME/.nix-profile
_JAVA_OPTIONS=-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java

WINEPREFIX=$XDG_DATA_HOME/wineprefixes/default
PARALLEL_HOME=$XDG_CONFIG_HOME/parallel
W3M_DIR=$XDG_STATE_HOME/w3m
NSS_DB_DIR=$XDG_DATA_HOME/pki/nssdb

PYTHON_HISTORY=$XDG_STATE_HOME/python_history
PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
PYTHONUSERBASE=$XDG_DATA_HOME/python
PIP_CONFIG_FILE=$XDG_CONFIG_HOME/pip/pip.conf

NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
PNPM_HOME=$XDG_DATA_HOME/pnpm

XDG_CURRENT_DESKTOP=sway
XDG_SESSION_DESKTOP=sway
XDG_SESSION_TYPE=wayland

QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt6ct
QT_STYLE_OVERRIDE=kvantum
QT_QUICK_BACKEND=software

TERMINAL=foot
COLORTERM=truecolor

EDITOR=vim
VISUAL=vim
SYSTEMD_EDITOR=vim
export MANPAGER=vim -M +MANPAGER -c 'set ft=man nomod nolist nonu noma' -
